### ISSUE TITLE
AddThis buttons do not show on a collective.cover type

### ISSUE THREAD

**Issue by andreabrugiolo** [collective/collective.addthis#5]
I built my new homepage with collective.cover and the AddThis buttons do not appear on it.

They appear on all the other pages as expected.

I am running on Plone 4.3.

Could you please make this great software work with collective.cover types too?

Thank you very much for you attention and for your work

**Comment by toutpt** [comment]
The addthis button is displayed using a viewlet. Are you sure this is not because collective.cover doesn't display the corresponding viewlet manager ?

**Comment by andreabrugiolo** [comment]
Well, I suppose it is possible. I'll try to ask the collective.cover developers. Thank you for your answer

**Comment by andreabrugiolo** [comment]
The collective.cover developers confirm your hypothesis, therefore I am going to close this issue :-)

Thank you very much for your time!
